import Head from 'next/head'
import Image from 'next/image'

import Container from '@mui/material/Container'
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import Alert from '@mui/material/Alert';
import AlertTitle from '@mui/material/AlertTitle';

import NavBar from '../components/NavBar'
import Title from '../components/Title'
import FavouriteBooks from '../components/FavouriteBooks'

import { useState } from 'react'

const FAVOURITE_BOOKS = [
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    rating: 9
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    rating: 8
  }
]

export default function Home() {
  const [books, setBooks ] = useState(FAVOURITE_BOOKS)
  const [title, setTitle ] = useState("")
  const [author, setAuthor ] = useState("")
  const [rating, setRating ] = useState("")
  const [newBook, setNewBook] = useState(FAVOURITE_BOOKS)
  

  const [errorMessage, setErrorMessage] = useState("")

  const handleSubmit = (event)=> {
    event.preventDefault()
    console.log("submitted")
    
    if (title.trim() === "" || author.trim() ==="" || rating.trim() === "") {
      setErrorMessage('Please enter all values correctly') 
      return
    }

    setErrorMessage("")
   
    let newBookItem = [{title},{author},{rating}]
    let newBookObj = {...newBookItem[0], ...newBookItem[1], ...newBookItem[2]}
    let newBookList = [newBookObj, ...newBook]
    // console.log(newBookList)
    setNewBook(newBookList)
    setAuthor("")
    setTitle("")
    setRating("")
 
  }
 

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar title={"Our Library"} />
      <main>
        <Container sx={{paddingTop: '2rem'}} maxWidth="md">
           <Paper sx={{ p: 2, display: 'flex', flexDirection: 'column', marginBottom: "2rem"}}>
              <Title>Add a New Favourite</Title>
              <form
              onSubmit={handleSubmit}
              >
                <Grid container spacing={2}>
                  <Grid item xs={6} sm={6}>
                    <TextField
                      id="title"
                      name="title"
                      label="Book Title"
                      fullWidth
                      variant="standard"
                      onChange={(e) => {setTitle(e.target.value)}}
                      value={title}
                    />
                  </Grid>
                  <Grid item xs={4} sm={2}>
                    <TextField
                      id="author"
                      name="author"
                      label="Author"
                      fullWidth
                      variant="standard"
                      onChange={(e) => {setAuthor(e.target.value)}}
                      value={author}
                    />
                  </Grid>
                  <Grid item xs={2} sm={2}>
                    <TextField
                      id="rating"
                      name="rating"
                      label="Rating"
                      fullWidth
                      variant="standard"
                      onChange={(e) => {setRating(e.target.value)}}
                      value={rating}
                    />
                  </Grid>
                  <Grid item xs={2} sm={2}>
                    <Button variant="contained" 
                     type="submit"
                     sx={{ mt: 1.5, ml: 1 }}>Add</Button>
                  </Grid>
                </Grid>
                <Grid item xs={10}>  
                {errorMessage !== "" &&
                <Alert severity="error" sx={{marginTop: "1rem"}}>
                  <AlertTitle>Error</AlertTitle>
                <strong>{errorMessage}</strong>
              </Alert>
                }
              </Grid>
              </form>

           </Paper>
          <FavouriteBooks books={newBook} />
          
        </Container>
      </main>
    </div>
  )
}
